{% set name = "libtool" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://alpha.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac9d4b8e072aa20d030d5ae039aba3b52bd7967b09e0c21f91f3e3dc1bbb8755

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - m4
    - help2man
    - autoconf
    - automake
    - make

outputs:
  - name: libltdl
    script: build_libltdl.sh
    build:
      run_exports:
        - {{ pin_subpackage('libltdl', max_pin='x.x') }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - m4
        - help2man
        - autoconf
        - automake
        - make
        - texinfo
        - patch
    about:
      license: LGPL-2.0-or-later
      license_file: libltdl/COPYING.LIB
  - name: libtool
    script: build_libtool.sh
    build:
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - m4
        - help2man
        - autoconf
        - automake
        - make
        - texinfo
        - patch
      host:
        - {{ pin_subpackage('libltdl', exact=true) }}
      run:
        - {{ pin_subpackage('libltdl', exact=true) }}
    test:
      requires:
        - {{ compiler('cxx') }}
    about:
      license: GPL-2.0-or-later
      license_file:  COPYING

about:
  home: https://www.gnu.org/software/libtool
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: The GNU Portable Library Tool
  description: |
    GNU libtool is a generic library support script. Libtool hides the
    complexity of using shared libraries behind a consistent, portable
    interface.
  doc_url: https://www.gnu.org/software/libtool/manual
  dev_url: https://git.savannah.gnu.org/cgit/libtool.git

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
    - jakirkham
    - mingwandroid
    - isuruf
