# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Q7cwT5KF0ZKLjEU59dVS0KpzUIGN/vILQ9HY6xNZJDXWVFp5M6UqAFGzZeLrNwRzUs2Mf8Pcfg1bKVdjWSQCMBKPT3oGzPnbJamvsQUw+CbFDcVxVdocckevRhcOLeiFEludLo8MbMz/iJKVETZDmRLClivVgpgVCik3juWZdudnVIvPpYG/6wgsfzaKof11WV5/341lkG/vzViktPZChjzCoEoh87lGBtFMFqNtOin84x3RZR0mzEP5wkOMVBteFghdGV2nZBWLTc+eU+sr2YlXlpCpAJ++NY3U2FS1GodAj1huXMPqiHM906nVrNO9Fw7nlczwKTx22hMYtUdcA6n5s4T8ByRQKlVJOMgcKQK+EY50+o9kbV9f/Cijeb82Mt49rJeWPXg7mCjKQ6BQeN9a2/XsQ5RjNPCjMl9uNR4YycBxqE969F4RuHFxmsHQphJ8cjckIrznQWE70rZhtrwgzD53kogTx3yfkZ+b5q9gQDOoWbt5cG8gPV0F1E5LkXK1UOx7ZYcOlEgiWiQ1o97S9RebY7NvHiLNVc96jHgxMImQf0qJ18CU+EEeFS4+WbFrfaHEeq5T+jE31hPiyuCX8yyqQSq/OWhDMsGJPwCt/nRT43vtqHJoF4PIdPL6+6JXUMr0yxaB4EgSLiRxirQN7mxa+aJ7O4KcyDCj0YI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
